// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtdedtueqwnlmbpwdjck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZGVkdHVlcXdubG1icHdkamNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjY0NTQsImV4cCI6MjA1ODE0MjQ1NH0.bfTEZsrnYfje11ip8DNlOtocEXrTYcSMAr60Gh-BeC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);